services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stream/hls:/tmp/hls
    ports:
      - "1935:1935"
      - "8081:8081"
  goapp:
    build:
      context: .
      dockerfile: Dockerfile.goapp
    ports:
    - "8080:8080"
    volumes:
      - ./thumbs:/thumbs
  # gif:
  #   image: bash:latest
  #   command: sh hls-to-gif.sh
  #   volumes:
  #     - ./hls-to-gif.sh:/hls-to-gif.sh
  #   ports:
  #     - "8080:8080"